### ISSUE TITLE
Error display when in "screen"

### ISSUE THREAD

**Issue by GF-Huang** [uoaerg/wavemon#85]
![B1xWRe5k9w](https://user-images.githubusercontent.com/4510984/103261612-155dc900-49dd-11eb-9dcf-aca7bb30d132.gif)

**Comment by grrtrr** [comment]
Hi @GF-Huang - what version is this?

Can you try to rebuild from `master` (v0.9.3)? There were a bunch of fixes recently that improved clearing the screen.
Need your collaboration this, since I am unable to reproduce this locally.

**Comment by GF-Huang** [comment]
`0.8.2`

**Comment by grrtrr** [comment]
Thank you - can you retry with `master` please? Most (possibly all) problems should be fixed.
There were a lot of problems on Raspberry Pi that were fixed since.

Regarding debian/ubuntu - I am not a maintainer - @jmccrohan did this in the past, I will check who is currently maintaining the package.

**Comment by GF-Huang** [comment]
`0.9.3` issue still exist.

![AmCocwKGoB](https://user-images.githubusercontent.com/4510984/103362978-f5212d80-4af4-11eb-80cb-a35874b2637c.gif)

**Comment by grrtrr** [comment]
Can you print the values of 
- `echo $TERM`
- `locale` (that is a command)

**Comment by GF-Huang** [comment]
![image](https://user-images.githubusercontent.com/4510984/103366209-f6eeef00-4afc-11eb-9ba7-35dde5cbcc31.png)

**Comment by grrtrr** [comment]
Ok, what value of `$TERM` do you get outside of `screen`? 
This could have to do with `xshell`, since it acts as a terminal emulator.
Does the problem persist on `putty` (I have tested with both putty and termius on Android, and they work for the en_CA UTF-8 locale),

**Comment by GF-Huang** [comment]
![image](https://user-images.githubusercontent.com/4510984/103366375-7b417200-4afd-11eb-979b-fbb1af214a2a.png)

**Comment by grrtrr** [comment]
How do applications like `htop`, `mc` look in this setting? 
One thing to try is `TERM=vt100 wavemon` - does the problem persist?

**Comment by GF-Huang** [comment]
I had try in Windows PowerShell (with in screen), issue still.

**Comment by GF-Huang** [comment]
![ROkad5Y7yB](https://user-images.githubusercontent.com/4510984/103366970-e17ac480-4afe-11eb-9b3b-95cdedcc2111.gif)

**Comment by GF-Huang** [comment]
`htop` works well, but I don't have `mc`.

**Comment by grrtrr** [comment]
Thank you for the details, I will work on reproducing (and hopefully fixing) that over the next couple of days.

**Comment by grrtrr** [comment]
Here is an update, but it looks this is going to be hard to fix:
- I am able to reproduce the problem,
- problem occurs regardless of xshell, putty etc,
- problem occurs with Chinese UTF-8 locale inside `screen`,
- outside `screen` this problem does not occur.

The problem has to do with (a) wide-character support, (b) box-drawing characters around the window, (c) `screen` capabilities and (d) locale. narrowed down the problem to the line-drawing routines in `ui.c`. By _disabling_ the box-drawing characters, the output is no longer garbled:
```diff
index 9a4a8b9..b7d42c0 100644
--- a/ui.c
+++ b/ui.c
@@ -28,7 +28,7 @@
 WINDOW *newwin_title(int y, int h, const char *title, bool nobottom)
 {
        WINDOW *win = newwin(h, WAV_WIDTH, y, 0);
-
+#if 0
 #ifdef HAVE_LIBNCURSESW
        const cchar_t * top_left  = y > 0 ? WACS_LTEE : WACS_ULCORNER;
        const cchar_t * top_right = y > 0 ? WACS_RTEE : WACS_URCORNER;
@@ -57,6 +57,7 @@ WINDOW *newwin_title(int y, int h, const char *title, bool nobottom)
                wborder(win, ACS_VLINE, ACS_VLINE, ACS_HLINE, ACS_HLINE,
                        top_left, top_right, ACS_LLCORNER, ACS_LRCORNER);
        }
+#endif
 #endif
        wattrset(win, COLOR_PAIR(CP_CYAN));
        mvwaddstr(win, 0, 2, title);
```
`htop` does not draw a box around its window. At the moment I am out of ideas of how to fix this. Plus, it is a corner case (does not happen when outside `screen`).

**Comment by grrtrr** [comment]
### Work-around

The following works:
```bash
> LC_ALL=C screen -U
> # alternatively:
> env -i TERM=$TERM screen -U
```
The `-U` is optional (enables utf-8 support explicitly).

**Comment by GF-Huang** [comment]
Thanks a lot. I will try these. 🌹

**Comment by grrtrr** [comment]
I tried with _midnight commander_ (`sudo apt-get install mc`) and it is the same problem inside `screen`,
the line-drawing characters lead to garbled display output. Using `LC_ALL=C screen` also helped.

**Comment by grrtrr** [comment]
@GF-Huang - I have thought about redesigning the layout to not use the line-drawing characters. I think I will not do that at this time, but maybe later. Will be adding the above work-around to the manpage, in the "trouble-shooting" section.

I notice that you use `sudo` to run `wavemon`. If you use this for the scan screen (which requires net-admin permissions),
you can also install it _suid-root_, using
```bash
> sudo make install suid-root
```
Then the next time, you can simply call it as `wavemon` and it will have the right privileges.

**Comment by GF-Huang** [comment]
Got it, thank you.
